<?php
/**
 * A list of required PHP extensions autogenerated by the build script.
 *
 * @package Cache
 */

$required_extensions = [
    'dom',
    'json',
    'libxml',
    'mbstring',
    'simplexml',
];
